
package rpc.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldImplementationService", targetNamespace = "http://webservice.rpc/", wsdlLocation = "http://localhost:6900/ws/hello?wsdl")
public class HelloWorldImplementationService
    extends Service
{

    private final static URL HELLOWORLDIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName HELLOWORLDIMPLEMENTATIONSERVICE_QNAME = new QName("http://webservice.rpc/", "HelloWorldImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6900/ws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        HELLOWORLDIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public HelloWorldImplementationService() {
        super(__getWsdlLocation(), HELLOWORLDIMPLEMENTATIONSERVICE_QNAME);
    }

    public HelloWorldImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLDIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public HelloWorldImplementationService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDIMPLEMENTATIONSERVICE_QNAME);
    }

    public HelloWorldImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLDIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public HelloWorldImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorldInterface
     */
    @WebEndpoint(name = "HelloWorldImplementationPort")
    public HelloWorldInterface getHelloWorldImplementationPort() {
        return super.getPort(new QName("http://webservice.rpc/", "HelloWorldImplementationPort"), HelloWorldInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldInterface
     */
    @WebEndpoint(name = "HelloWorldImplementationPort")
    public HelloWorldInterface getHelloWorldImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.rpc/", "HelloWorldImplementationPort"), HelloWorldInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw HELLOWORLDIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return HELLOWORLDIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
